### ISSUE TITLE
cmdargs, static issue.

### ISSUE THREAD

**Issue by ilanpillemer** [gameontext/regutil#9]
There is some edge case where `cmdargs` behaves incorrectly, due to it being static but the actual data its linking to, being instance variables. This is specifically occurring with the method name value.

It occurs when you run a GET via main, and then run a POST afterwards without providing the method and assuming the default.

This edge case will probably never occur in actual usage via command line; but could occur in other scenarios where the utility is being used programmatically and the POST is being assumed.

(I have this fixed in a local branch which I will send as a pull request, after my earlier pull request that fixed up formatting is accepted, so as to make reviewing the changes simpler)

**Comment by ebullient** [comment]
Other PR merged.. sorry for the lag, I missed it somehow.
